//
//  Tests.cpp
//  asm
//
//  Created by Manuel Deneu on 26/03/2025.
//

#include "Tests.hpp"
#include "Assembler.hpp"
#include "Disassembler.hpp"
#include <assert.h>

static void TestValidInstruction(const std::string &inCode) {
    Assembler a(inCode);
    auto b = a.generate();
    assert(a.getError() == std::nullopt);
    assert(b.size() > 0);
    Disassembler d(b);
    d.params.noAutogeneratedComments = true;
    auto code = d.generate();
    code.resize(code.size() - 1); // remove last \n
    assert(code == inCode);
}

static void RunTests1() {
    TestValidInstruction("CLS");
    TestValidInstruction("RET");
    TestValidInstruction("LD V2, 0X78");
    TestValidInstruction("LD I, 0X500");
    TestValidInstruction("LD V3, 0X1");
    TestValidInstruction("LD VC, 0X1");
    TestValidInstruction("LD V4, 0X1");
    TestValidInstruction("LD V1, K");
    TestValidInstruction("LD VD, K");
    TestValidInstruction("LD ST, V2");
    TestValidInstruction("LD F, V1");
    TestValidInstruction("DRW V3, V4, 0X5");
    TestValidInstruction("JP 0X200");
    TestValidInstruction("JP V0, 0X200");
    TestValidInstruction("LD V1, 0XA");
    TestValidInstruction("LD VB, DT");
    TestValidInstruction("LD V4, DT");
    TestValidInstruction("LD V1, I");
    TestValidInstruction("LD VA, I");
    TestValidInstruction("SE VA, 0X12");
    TestValidInstruction("LD DT, V3");
    TestValidInstruction("SKNP V6");
    TestValidInstruction("SNE V2, VA");
    TestValidInstruction("SNE V2, 0X12");
    TestValidInstruction("ADD V0, 0X1");
    TestValidInstruction("ADD V0, VC");
    TestValidInstruction("ADD I, VC");
}

static void TestInvalidASM(const std::string &code) {
    Assembler a(code);
    auto b = a.generate();
    assert(b.size() == 0);
    assert(a.getError() != std::nullopt);
    assert(a.getError().value().line == 1);
}
static void RunTests2() {
    TestInvalidASM("lol\n");
    TestInvalidASM("LD\n");
    TestInvalidASM("LD G, Vx");
    TestInvalidASM("LD V2\n");
    TestInvalidASM("LD V2, lol");
    TestInvalidASM("JP V0, addr");
    TestInvalidASM("LD I, lol");
    TestInvalidASM("LD G abcd");
    TestInvalidASM("LD ST, abcd");
    TestInvalidASM("LD ST, v15");
    TestInvalidASM("LD F, lol");
    TestInvalidASM("LD F, v-1");
    TestInvalidASM("LD Vx, Vy");
    TestInvalidASM("LD Vaa, Vff");
    TestInvalidASM("DRW foo, V67, foo");
    TestInvalidASM("JP bar");
    TestInvalidASM("DRW V3, VT, 0x5");
}

void RunTests() {
    RunTests1();
    RunTests2();
}
